code --install-extension formulahendry.code-runner --force
code --install-extension grapecity.gc-excelviewer --force
code --install-extension hilalh.hyper-dracula-vscode-theme --force
code --install-extension miguelsolorio.symbols --force
code --install-extension ms-python.debugpy --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-python.vscode-python-envs --force
code --install-extension naumovs.color-highlight --force
code --install-extension qwtel.sqlite-viewer --force
code --install-extension redhat.vscode-yaml --force
code --install-extension ritwickdey.liveserver --force
code --install-extension vscodevim.vim --force