code --install-extension brandonkirbyson.vscode-animations --force
code --install-extension drcika.apc-extension --force
code --install-extension hilalh.hyper-dracula-vscode-theme --force
code --install-extension miguelsolorio.symbols --force
code --install-extension ms-python.python --force
code --install-extension ms-python.vscode-pylance --force
code --install-extension ms-vscode-remote.remote-wsl --force
code --install-extension naumovs.color-highlight --force
code --install-extension ritwickdey.liveserver --force
code --install-extension visualstudioexptteam.vscodeintellicode --force
