code --uninstall-extension brandonkirbyson.vscode-animations
code --uninstall-extension drcika.apc-extension
code --uninstall-extension hilalh.hyper-dracula-vscode-theme
code --uninstall-extension miguelsolorio.symbols
code --uninstall-extension ms-python.python
code --uninstall-extension ms-python.vscode-pylance
code --uninstall-extension ms-vscode-remote.remote-wsl
code --uninstall-extension naumovs.color-highlight
code --uninstall-extension ritwickdey.liveserver
code --uninstall-extension visualstudioexptteam.vscodeintellicode
