call code --uninstall-extension formulahendry.code-runner
call code --uninstall-extension grapecity.gc-excelviewer
call code --uninstall-extension hilalh.hyper-dracula-vscode-theme
call code --uninstall-extension miguelsolorio.symbols
call code --uninstall-extension ms-python.debugpy
call code --uninstall-extension ms-python.python
call code --uninstall-extension ms-python.vscode-pylance
call code --uninstall-extension ms-python.vscode-python-envs
call code --uninstall-extension ms-vscode-remote.remote-wsl
call code --uninstall-extension naumovs.color-highlight
call code --uninstall-extension qwtel.sqlite-viewer
call code --uninstall-extension redhat.vscode-yaml
call code --uninstall-extension ritwickdey.liveserver
call code --uninstall-extension vscodevim.vim