call code --uninstall-extension brandonkirbyson.vscode-animations
call code --uninstall-extension drcika.apc-extension
call code --uninstall-extension hilalh.hyper-dracula-vscode-theme
call code --uninstall-extension miguelsolorio.symbols
call code --uninstall-extension ms-python.python
call code --uninstall-extension ms-python.vscode-pylance
call code --uninstall-extension ms-vscode-remote.remote-wsl
call code --uninstall-extension naumovs.color-highlight
call code --uninstall-extension ritwickdey.liveserver
call code --uninstall-extension visualstudioexptteam.vscodeintellicode
